### PR TITLE
Legitimacy checks through PKHex [Pseudocode Implementation]

### PR DESCRIPTION
**Pull request by Gannio**
This is a quick attempt at implementing a legitimacy check using PKHex's Core, having both basic sanity checks and optional, but thorough legitimacy checks. However, since I don't have the hardware necessary to properly test the server (and even if I did my college blocks ports making testing difficult), I don't have a means to actually test this code, so it should be tested to make sure it does not cause compiler errors when running.

The version of the core used is the one present in PKHex's source on 9/3/2019, however it contains an extra method to specifically check for ball seals, as they could cause irremovable Pokemon if not checked for. The validation method is also currently only implemented for Gen IV, however it shouldn't take too much work to add to Gen V (the main difference is changing a 0 to a 1). Finally, the method for decrypting the encrypted data (PKX.DecryptArray45) may not actually work properly, as I normally used a method inherent to Shiny2+1/2 to decrypt data rather than PKHex's decryption method.

Also PKHex uses GPL 3 as its license, however I don't think that particular license would violate anything the current program uses.

(For the file changes: Discarding the addition of PKHex as a reference in the gts class, pokemondpds.ashx.cs was the only file modified)

### CODE REVIEW

**Comment by mm201** [comment]
For starters, please use the PKHex Nuget package. I don’t want 9000 files cluttering up my repo. If you have made changes to the PKHex library, make a private fork of it and include it as a submodule. 

Additionally, pkhex isn’t going to work for battle tower.

**Comment by Gannio** [comment]
I've updated it to include the Nuget package, however I had to update the framework for GTS from 4.0 to 4.6 to install it, and I'm unsure if that will affect the compiled program any (the point I can get to in compilation with my setup is the same as it was without 4.6). I also made replaced the Ball Capsule method with a basic byte check on the data within pokemondpds.ashx.cs itself, so whenever new PKHex releases come out they can be installed without having to add a new method each time.

**Comment by mm201** [comment]
Just to let you know I haven't forgotten this, but I need to test it aggressively to be sure there aren't false positives and I want to get some admin functions in place first to assist with that.

**Comment by nathanielcwm** [comment]
I guess this solves #3?

**Comment by mm201** [comment]
Closing because the patches here have been superseded. Further discussion can continue in #3.

**Pull request closed without merging**
